### ISSUE TITLE
Provide a way to stash credentials for different git hosts

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/git-client#69]
Add a check for a hidden file in the home directory, like `.gitu-config`

The file can be a yaml file with a section for authentications:

```yaml
credentials:
  - host: github.com
    username: <username>
    password: <password>
  - host: github.ibm.com
    username: <username>
    password: <password>
```
